### ISSUE TITLE
Outdated setup.exe

### ISSUE THREAD

**Issue by roadfox** [CybeSystems/CygwinPortable#13]
Got the following message when trying to run "Cygwin Setup"

"The current ini file is from a newer version of setup.exe. If you have any trouble installing, please download a fresh version from http://www.cygwin.com/setup.exe"

To solve this this, download: http://www.cygwin.com/setup-x86.exe

And replace [Cygwin Portable Install folder]\App\Runtime\Cygwin\CygwinConfig.exe with the downloaded file

**Comment by tYYGH** [comment]
Why is this issue closed?
There should be some answer or documentation somewhere, to explain how to:

* either use an updated setup.exe in an existing CygwinPortable installation,
* or upgrade an existing CygwinPortable installation with the latest one.

**Comment by tYYGH** [comment]
For anyone finding this page, look here: https://github.com/CybeSystems/CygwinPortable/issues/25
