### ISSUE TITLE
download links not working

### ISSUE THREAD

**Issue by pancheto** [CybeSystems/CygwinPortable#16]
great work. just to note that the download manager on the cubesystems website
http://www.cybesystems.com/index.php?option=com_jdownloads&view=downloads&Itemid=196
doesn't seem to be serving the precompiled binaries the README.md file mentions.

**Comment by alfio8788** [comment]
I can confirm this, everytime i try to download the files it just doesn't happen (the reason is jdownloader)

**Comment by CybeSystems** [comment]
Please try again -> Fixed links on Homepage :-)
