### ISSUE TITLE
Example Files?

### ISSUE THREAD

**Issue by alfio8788** [CybeSystems/CygwinPortable#17]
I would like to have some example files as compiling the app and starting it leads to errors right away (missing Packages folder), creating it leads to another error cause the folder just created is empty and the program is expecting a filled array with txt files...

```
DirectoryInfo diSource = new DirectoryInfo(Globals.AppPath + "\\DefaultData\\Packages");
            foreach (FileInfo fi in diSource.GetFiles())
            {
                comboBox_packages.Items.Add(fi.Name.Replace(".txt",""));
            }
            comboBox_packages.SelectedIndex = 0;
```

Some documentation or example files to understand perfectly how it works would be nice

**Comment by CybeSystems** [comment]
Please try again -> This folder was filtered by gitignore... Should now work

**Comment by alfio8788** [comment]
Thank you for fixing this, i confirm downloads are now working
