### ISSUE TITLE
Cygwin Portable cannot be started!!

### ISSUE THREAD

**Issue by xiaoyun4** [CybeSystems/CygwinPortable#33]
i am confused when i download this file and find CygwinPortable-master\Other\source\CygwinPortable.exe. when i try to run CygwinPortable.exe, an error is 

![1](https://user-images.githubusercontent.com/20512673/29499937-e6f2d1b0-864d-11e7-840a-379e42737e5d.png)

what is the matter? 
my pc is win7

**Comment by djohns451** [comment]
@xiaoyun4 You'll need to either build with the provided scripts, or grab a release from here: [](http://www.cybesystems.com/index.php?option=com_jdownloads&view=downloads&Itemid=196)

**Comment by djohns451** [comment]
Keep in mind that the provided releases are old, and could use updating after setting up.

**Comment by xiaoyun4** [comment]
Thank you very much, it works.

**Comment by djohns451** [comment]
Please close the issue, if your problem is solved. :)
